## define data schema so that values can be remapped
v_schema <- function(type) {
    switch(type,
           ## https://www.fivb.org/VisSDK/VisWebService/PlayerVolleyPosition.html
           "Player Volley Position" = tribble(~from, ~to, ~description,
                                              0L, "Unknown", "Unknown",
                                              1L, "Setter", "Setter",
                                              2L, "WingSpiker", "Wing spiker",
                                              3L, "MiddleBlocker", "Middle blocker",
                                              4L, "Libero", "Libero",
                                              5L, "Universal", "Universal",
                                              6L, "OppositeSpiker", "Opposite spiker"),
           ## https://www.fivb.org/VisSDK/VisWebService/PlayerBeachPosition.html
           "Player Beach Position" = tribble(~from, ~to, ~description,
                                             0L, "Unknown", "Unknown",
                                             1L, "RightBlocker", "Right blocker",
                                             2L, "LeftBlocker", "Left blocker",
                                             3L, "RightDefender", "Right defender",
                                             4L, "LeftDefender", "Left defender",
                                             5L, "Right", "Right",
                                             6L, "Left", "Left",
                                             7L, "Universal", "Universal"),
           ## https://www.fivb.org/VisSDK/VisWebService/#FederationCode.html
           "Federation Code" = tribble(~code, ~federation,
                                       "ALB", "Albania",
                                       "AFG", "Afghanistan",
                                       "AGU", "Anguilla",
                                       "AHO", "Netherlands Antilles",
                                       "ALG", "Algeria",
                                       "AND", "Andorra",
                                       "ANG", "Angola",
                                       "ANT", "Antigua and Barbuda",
                                       "ARG", "Argentina",
                                       "ARM", "Armenia",
                                       "ARU", "Aruba",
                                       "ASA", "American Samoa",
                                       "AUS", "Australia",
                                       "AUT", "Austria",
                                       "AZE", "Azerbaijan",
                                       "BAH", "Bahamas",
                                       "BAN", "Bangladesh",
                                       "BAR", "Barbados",
                                       "BDI", "Burundi",
                                       "BEL", "Belgium",
                                       "BEN", "Benin",
                                       "BER", "Bermuda",
                                       "BHU", "Bhutan",
                                       "BIH", "Bosnia and Herzegovina",
                                       "BIZ", "Belize",
                                       "BLR", "Belarus",
                                       "BOL", "Bolivia",
                                       "BON", "Bonaire",
                                       "BOT", "Botswana",
                                       "BRA", "Brazil",
                                       "BRN", "Bahrain",
                                       "BRU", "Brunei Darussalam",
                                       "BUL", "Bulgaria",
                                       "BUR", "Burkina Faso",
                                       "CAF", "Central African Republic",
                                       "CAM", "Cambodia",
                                       "CAN", "Canada",
                                       "CAY", "Cayman Islands",
                                       "CGO", "Congo",
                                       "CHA", "Chad",
                                       "CHI", "Chile",
                                       "CHN", "China",
                                       "CIV", "C\uf4te d'Ivoire",
                                       "CMR", "Cameroon",
                                       "COD", "Congo, the Democratic Republic of the",
                                       "COK", "Cook Islands",
                                       "COL", "Colombia",
                                       "COM", "Comoros",
                                       "CPV", "Cape Verde",
                                       "CRC", "Costa Rica",
                                       "CRO", "Croatia",
                                       "CUB", "Cuba",
                                       "CUR", "Cura\ue7ao",
                                       "CYP", "Cyprus",
                                       "CZE", "Czech Republic",
                                       "DEN", "Denmark",
                                       "DJI", "Djibouti",
                                       "DMA", "Dominica",
                                       "DOM", "Dominican Republic",
                                       "ECU", "Ecuador",
                                       "EGY", "Egypt",
                                       "ENG", "England",
                                       "ERT", "Eritrea",
                                       "ESA", "El Salvador",
                                       "ESP", "Spain",
                                       "EST", "Estonia",
                                       "ETH", "Ethiopia",
                                       "EUX", "Sint Eustatius",
                                       "FER", "Faroe Islands",
                                       "FGU", "French Guiana",
                                       "FIJ", "Fiji",
                                       "FIN", "Finland",
                                       "FIV", "FIVB", ## Not a federation, but is used as some special cases.
                                       "FRA", "France",
                                       "FSM", "Micronesia, Federated States of",
                                       "GAB", "Gabon",
                                       "GAM", "Gambia",
                                       "GBR", "Great Britain", ## Not a federation, but must be used for some events, such as the Olympic Games, because they are working with countries.
                                       "GBS", "Guinea-Bissau",
                                       "GDP", "Guadeloupe",
                                       "GEO", "Georgia",
                                       "GEQ", "Equatorial Guinea",
                                       "GER", "Germany",
                                       "GHA", "Ghana",
                                       "GIB", "Gibraltar",
                                       "GRE", "Greece",
                                       "GRL", "Greenland",
                                       "GRN", "Grenada",
                                       "GUA", "Guatemala",
                                       "GUI", "Guinea",
                                       "GUM", "Guam",
                                       "GUY", "Guyana",
                                       "HAI", "Haiti",
                                       "HKG", "Hong Kong",
                                       "HON", "Honduras",
                                       "HUN", "Hungary",
                                       "INA", "Indonesia",
                                       "IND", "India",
                                       "IRI", "Iran",
                                       "IRL", "Ireland",
                                       "IRQ", "Iraq",
                                       "ISL", "Iceland",
                                       "ISR", "Israel",
                                       "ISV", "Virgin Islands, U.S.",
                                       "ITA", "Italy",
                                       "IVB", "Virgin Islands, British",
                                       "JAM", "Jamaica",
                                       "JOR", "Jordan",
                                       "JPN", "Japan",
                                       "KAZ", "Kazakhstan",
                                       "KEN", "Kenya",
                                       "KGZ", "Kyrgyzstan",
                                       "KIR", "Kiribati",
                                       "KOR", "Korea, Republic of",
                                       "KOS", "Kosovo",
                                       "KSA", "Saudi Arabia",
                                       "KUW", "Kuwait",
                                       "LAO", "Lao People's Democratic Republic",
                                       "LAT", "Latvia",
                                       "LBA", "Libya",
                                       "LBR", "Liberia",
                                       "LCA", "Saint Lucia",
                                       "LES", "Lesotho",
                                       "LIB", "Lebanon",
                                       "LIE", "Liechtenstein",
                                       "LTU", "Lithuania",
                                       "LUX", "Luxembourg",
                                       "MAC", "Macao",
                                       "MAD", "Madagascar",
                                       "MAR", "Morocco",
                                       "MAS", "Malaysia",
                                       "MAW", "Malawi",
                                       "MDV", "Maldives",
                                       "MEX", "Mexico",
                                       "MGL", "Mongolia",
                                       "MKD", "Macedonia, the Former Yugoslav Republic of",
                                       "MLD", "Moldova",
                                       "MLI", "Mali",
                                       "MLT", "Malta",
                                       "MNE", "Montenegro",
                                       "MON", "Monaco",
                                       "MOZ", "Mozambique",
                                       "MQE", "Martinique",
                                       "MRI", "Mauritius",
                                       "MSH", "Marshall Islands",
                                       "MTN", "Mauritania",
                                       "MTS", "Montserrat",
                                       "MYA", "Myanmar",
                                       "NAM", "Namibia",
                                       "NCA", "Nicaragua",
                                       "NED", "Netherlands",
                                       "NEP", "Nepal",
                                       "NGR", "Nigeria",
                                       "NIG", "Niger",
                                       "NIR", "Northern Ireland",
                                       "NIU", "Niue",
                                       "NOR", "Norway",
                                       "NRU", "Nauru",
                                       "NZL", "New Zealand",
                                       "OMA", "Oman",
                                       "PAK", "Pakistan",
                                       "PAN", "Panama",
                                       "PAR", "Paraguay",
                                       "PAU", "Palau",
                                       "PER", "Peru",
                                       "PHI", "Philippines",
                                       "PLE", "Palestinian Territory, Occupied",
                                       "PLY", "French Polynesia",
                                       "PNG", "Papua New Guinea",
                                       "POL", "Poland",
                                       "POR", "Portugal",
                                       "PRK", "Korea, Democratic People's Republic of",
                                       "PUR", "Puerto Rico",
                                       "QAT", "Qatar",
                                       "ROU", "Romania",
                                       "RSA", "South Africa",
                                       "RUS", "Russia",
                                       "RWA", "Rwanda",
                                       "SAB", "Saba",
                                       "SAI", "Northern Mariana Islands",
                                       "SAM", "Samoa",
                                       "SCO", "Scotland",
                                       "SEN", "Senegal",
                                       "SEY", "Seychelles",
                                       "SKN", "Saint Kitts and Nevis",
                                       "SIN", "Singapore",
                                       "SLE", "Sierra Leone",
                                       "SLO", "Slovenia",
                                       "SMA", "Saint Martin (French part)",
                                       "SMR", "San Marino",
                                       "SOL", "Solomon Islands",
                                       "SOM", "Somalia",
                                       "SRB", "Serbia",
                                       "SRI", "Sri Lanka",
                                       "STP", "Sao Tome and Principe",
                                       "SUD", "Sudan",
                                       "SUI", "Switzerland",
                                       "SUR", "Suriname",
                                       "SVK", "Slovakia",
                                       "SWE", "Sweden",
                                       "SWZ", "Swaziland",
                                       "SXM", "Sint Maarten (Dutch part)",
                                       "SYR", "Syrian Arab Republic",
                                       "TAN", "Tanzania",
                                       "TCI", "Turks & Caicos Islands",
                                       "TGA", "Tonga",
                                       "THA", "Thailand",
                                       "TJK", "Tajikistan",
                                       "TKM", "Turkmenistan",
                                       "TLS", "Timor-Leste",
                                       "TOG", "Togo",
                                       "TPE", "Taiwan, Province of China",
                                       "TTO", "Trinidad and Tobago",
                                       "TUN", "Tunisia",
                                       "TUR", "Turkey",
                                       "TUV", "Tuvalu",
                                       "UAE", "United Arab Emirates",
                                       "UGA", "Uganda",
                                       "UKR", "Ukraine",
                                       "URU", "Uruguay",
                                       "USA", "United States",
                                       "UZB", "Uzbekistan",
                                       "VAN", "Vanuatu",
                                       "VEN", "Venezuela",
                                       "VIE", "Viet Nam",
                                       "VIN", "Saint Vincent and the Grenadines",
                                       "WAL", "Wales",
                                       "YEM", "Yemen",
                                       "ZAM", "Zambia",
                                       "ZIM", "Zimbabwe"),
           stop("unexpected schema type: ", type)
           )
}
