#' Return the fields for a given VIS data type
#'
#' @references \url{https://www.fivb.org/VisSDK/VisWebService/}
#'
#' @param type string: the data type, currently one of "Volleyball Tournament", "Volleyball Tournament Filter", "Volleyball Tournament Ranking", "Volleyball Match", "Volleyball Match Filter", "Volleyball Pool", "Volleyball Pool Filter", "Volleyball Pool Ranking", "Volleyball Team", "Volleyball Team Filter", "Volleyball Player", "Volleyball Player Filter", "Volleyball Player Ranking", "Volleyball Statistics"
#'
#' @return A character vector of field names
#'
#' @examples
#' v_fields("Volleyball Tournament")
#'
#' @export
v_fields <- function(type) {
  switch(type,
    "Press Release Text" = c("No", "Version", "Accepted", "AdditionalInformation", "AstFormat", "Author", "Headline", "Introduction", "KeyStatistics", "Keywords", "Language", "LanguageEnglishName", "LanguageNativeName", "NoRelease", "PhotoTitle", "Quotes", "Status", "Text", "TextAst", "TwitterText", "TwitterUrl", "Category", "DateTime", "IsVideoLive", "NoMatch", "PublishOnBeach", "PublishOnDevelopment", "PublishOnFivb", "PublishOnHeadlines", "PublishOnHome", "PublishOnMedical", "PublishOnMsdp", "PublishOnPresident", "PublishOnRefereeingRules", "PublishOnTechnicalCoach", "PublishOnTournament", "PublishOnTwitter", "PublishOnVolley", "PublishOnWorldVolleyNews", "Source", "SourceCategory", "SpecialType", "TeamCode", "TournamentCode", "Url", "ValidFrom", "ValidTo", "VideoUri"),
    "Press Release" = c("Category", "DateTime", "DeletedDT", "Languages", "LastChangeDT", "LastChangeUsername", "No", "NoMatch", "PublishOnBeach", "PublishOnDevelopment", "PublishOnENews", "PublishOnFivb", "PublishOnHeadlines", "PublishOnHome", "PublishOnMedical", "PublishOnPresident", "PublishOnRefereeingRules", "PublishOnTechnicalCoach", "PublishOnTournament", "PublishOnTwitter", "PublishOnVolley", "PublishOnVolleyballWorld", "PublishOnWorldVolleyNews", "Source", "SourceCategory", "SpecialType", "TeamCode", "TournamentCode", "Url", "Version"),
    "Event" = c("AccreditationEndDate", "AccreditationStartDate", "Code", "CountryCode", "EndDate", "ExpensesCurrencyCode", "HasBeachTournament", "HasMenTournament", "HasSnowTournament", "HasVolleyTournament", "HasWomenTournament", "IsVisManaged", "Location", "Name", "No", "NoLogoImage", "NoParentEvent", "OrganizerCode", "OrganizerType", "StartDate", "Status", "Type", "Version", "InfoFederation", "InfoFormat", "InfoHotels", "InfoLocation", "InfoMedia", "InfoOrganizer", "InfoPresentation", "InfoSchedule", "InfoUseful", "Checklist", "Content", "AuxiliaryPersons", "Logos"),
    "Beach Tournament Ranking" = c("EarnedPointsTeam", "EarningsTotalTeam", "Position", "Rank", "TeamFederationCode", "TeamName"),
    "Beach Round Ranking" = c("MatchesLost", "MatchesWon", "MatchPoints", "Position", "Rank", "TeamFederationCode", "TeamName"),
    "Beach Team" = c("ConfederationCode", "CountryCode", "EarnedPointsPlayer", "EarnedPointsPlayerConfederation", "EarnedPointsTeam", "EarnedPointsTeamConfederation", "EarningsBonusPlayer", "EarningsBonusTeam", "EarningsPlayer", "EarningsTeam", "EarningsTotalPlayer", "EarningsTotalTeam", "EntryPoints", "EntryPoints1", "EntryPoints2", "FederationCode", "FederationRankingPoints", "FederationRankingPoints1", "FederationRankingPoints2", "IsInConfederationQuota", "IsInFederationQuota", "IsInMainDraw", "IsInQualification", "IsLockedInMainDraw", "MainDrawSeed", "MainDrawSeed1", "MainDrawSeed2", "Name", "NbParticipationsInMajorTournaments", "NbRank1InMajorTournaments", "NbRank2InMajorTournaments", "NbRank3InMajorTournaments", "No", "NoBiographyText", "NoPlayer1", "NoPlayer2", "NoShirt1", "NoShirt2", "NoTournament", "Player1BeachPosition", "Player1Birthdate", "Player1BirthPlace", "Player1FederationCode", "Player1FirstName", "Player1Height", "Player1LastName", "Player1TeamName", "Player1Weight", "Player2BeachPosition", "Player2Birthdate", "Player2BirthPlace", "Player2FederationCode", "Player2FirstName", "Player2Height", "Player2LastName", "Player2TeamName", "Player2Weight", "PositionInDispatch", "PositionInEntry", "PositionInMainDraw", "PositionInQualification", "PositionInQuota", "PositionInReserve", "PreviousEarningsInMajorTournaments", "QualificationPoints", "QualificationPoints1", "QualificationPoints2", "Rank", "SeedTechnicalPoints", "SeedTechnicalPoints1", "SeedTechnicalPoints2", "Status", "TechnicalPoints", "TechnicalPoints1", "TechnicalPoints2", "TournamentCode", "TournamentEndDateMainDraw", "TournamentName", "TournamentSeason", "TournamentSeed", "TournamentStatus", "TournamentTitle", "TournamentType", "Type", "WorldTourRanking", "Version"),
    "Beach Round" = c("No", "Version", "Bracket", "Code", "EndDate", "Name", "NbViewRanking", "Order", "NoTournament", "Phase", "RankingInformation", "RankingMethod", "RankMethod", "StartDate"),
    "Beach Match" = c("AcquisitionMethod", "AreCourtAndTimePublished", "BeginDateTimeUtc", "City", "Court", "DurationSet1", "DurationSet2", "DurationSet3", "DurationSet4", "DurationSet5", "EndDateTimeUtc", "FastestServeTeamAPlayer1", "FastestServeTeamAPlayer2", "FastestServeTeamBPlayer1", "FastestServeTeamBPlayer2", "Format", "Humidity", "LiveScoreSource", "LiveStreamUri", "LocalDate", "LocalTime", "LocalTimeOffset", "LoserRank", "LoserRoundRank", "MatchPointsA", "MatchPointsB", "MatchResultText", "NbLiveScoreUpload", "NbSpectators", "No", "NoDocumentReport", "NoEvent", "NoInTournament", "NoInTournamentForImages", "NoPlayerA1", "NoPlayerA2", "NoPlayerB1", "NoPlayerB2", "NoReferee1", "NoReferee2", "NoRefereeChallenge", "NoRound", "NoTeamA", "NoTeamB", "NoTournament", "Personnel", "PointsTeamASet1", "PointsTeamASet2", "PointsTeamASet3", "PointsTeamASet4", "PointsTeamASet5", "PointsTeamBSet1", "PointsTeamBSet2", "PointsTeamBSet3", "PointsTeamBSet4", "PointsTeamBSet5", "Referee1FederationCode", "Referee1Name", "Referee2FederationCode", "Referee2Name", "ResultType", "ResultTypeText", "RoundBracket", "RoundCode", "RoundName", "RoundPhase", "SetsResultsText", "Status", "TeamAFederationCode", "TeamAName", "TeamAPositionInMainDraw", "TeamAPositionInQualification", "TeamAText", "TeamAType", "TeamBFederationCode", "TeamBName", "TeamBPositionInMainDraw", "TeamBPositionInQualification", "TeamBText", "TeamBType", "Temperature", "TimeZone", "TournamentCode", "TournamentGender", "TournamentName", "TournamentTitle", "TournamentType", "UtcDate", "UtcTime", "Venue", "Version", "WinnerRank", "WinnerRoundRank"),
    "Beach World Tour Ranking" = c("EarnedPointsPlayer", "EarnedPointsTeam", "EarningsBonusPlayer", "EarningsBonusTeam", "EarningsPlayer", "EarningsTeam", "EarningsTotalPlayer", "EarningsTotalTeam", "HasTournamentsRemoved", "NbParticipations", "NoPlayer1", "NoPlayer2", "Position", "Rank", "TeamFederationCode", "TeamName"),
    "Beach Olympic Selection Ranking" = c("Position", "GamesYear", "NoPlayer1", "NoPlayer2", "TeamName", "TeamCountryCode", "NbParticipations", "SelectionRank", "Points", "Status"),
    "Beach Tournament" = c("Actions", "Code", "CountryCode", "CountryName", "Deadline", "DefaultLocalTimeOffset", "DefaultMatchFormat", "DefaultTimeZone", "DispatchMethod", "DispatchStatus", "EarningsCurrencyCode", "EndDateFederationQuota", "EndDateMainDraw", "EndDateQualification", "EntryPointsBaseDate", "EntryPointsDayOffset", "EntryPointsTemplateNo", "EventAuxiliaryPersons", "EventLogos", "FederationCode", "Gender", "IsVisManaged", "Logos", "MatchPointsMethod", "MaxRegisterFederation", "MaxRegisterHost", "MaxReserveTeams", "MaxTeamsDispatchFederation", "MaxTeamsDispatchHost", "MaxTeamsFederation", "MaxTeamsHost", "MaxTeamsMainDrawFederation", "MaxTeamsMainDrawHost", "MinConfederationTeams", "MinTeamsDispatchHost", "Name", "NbTeamsFromQualification", "NbTeamsMainDraw", "NbTeamsQualification", "NbUploads", "NbWildCards", "No", "NoEvent", "NoTemplateEarnedPoints", "NoTemplatePrizeMoney", "OrganizerCode", "OrganizerType", "Parameters", "PreliminaryInquiryMainDraw", "PreliminaryInquiryQualification", "Season", "SeedPointsBaseDate", "SeedPointsDayOffset", "SeedPointsTemplateNo", "StartDate", "StartDateFederationQuota", "StartDateMainDraw", "StartDateQualification", "Status", "TechnicalEntryPointsTemplateNo", "TechnicalSeedPointsTemplateNo", "Title", "Type", "Version", "WebSite"),
    "Referee" = c("No", "Gender", "FirstName", "LastName", "Birthdate", "FederationCode"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyTournament_members.html
    "Volleyball Tournament" = c("Actions", "ArticleBaseUrl", "BuyTicketsUrl", "City", "Code", "ContainsLiveComments", "ContainsLiveScores", "ContainsMatches", "ContainsMatchResults", "ContainsNews", "ContainsPictures", "ContainsPlayByPlay", "ContainsPlayers", "ContainsRanking", "ContainsStatistics", "ContainsTeams", "ContainsVideos", "ContainsVideoTracking", "CountryCode", "CountryName", "Dates", "DeadlineO2", "DeadlineO2A", "DeadlineO2bis", "DefaultMatchFormat", "DefaultPlayersRanking", "DeletedDT", "EndDate", "EventLogos", "Gender", "IsFreeEntrance", "IsVisManaged", "LastChangeDT", "LastChangeUser", "LastChangeUsername", "Logos", "Matches", "MaxNbPlayersO2", "MaxNbPlayersO2A", "MaxNbPlayersO2bis", "MaxNbTeamOfficialsOnBench", "MaxNbTeams", "Name", "No", "NoArticlePresentation", "NoConfederation", "NoEvent", "NoImageLogo", "NoImageOrganizerLogo", "NoImagePublicity", "OrganizerCode", "OrganizerName", "OrganizerType", "PlayerDisplayMethod", "PoolName", "Pools", "Presentation", "PublishOnMsdp", "RoundCode", "Season", "ShortName", "ShortNameOrName", "StartDate", "Status", "Teams", "TeamType", "TournamentLogos", "Type", "Version", "WebSite"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyTournamentFilter_members.html
    "Volleyball Tournament Filter" = c("Code", "CountryCode", "FirstDate", "Genders", "IsVisManaged", "LastDate", "NoConfederation", "NoEvent", "Numbers", "PublishOnMsdp", "Seasons", "Statuses", "Types"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyTournamentRankingEntry_members.html
    "Volleyball Tournament Ranking" = c("eletedDT", "LastChangeDT", "LastChangeUser", "LastChangeUsername", "No", "NoTeam", "NoTournament", "Position", "Rank", "RankText", "RankTextWithRepeat", "TeamCode", "TeamName", "TeamNameOrCodeOrSource", "TeamSource", "UserText", "Version"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyMatch_members.html
    "Volleyball Match" = c("AcquisitionMethod", "AssistantScorerCountryCode", "AssistantScorerFirstName", "AssistantScorerLastName", "BeginDateTimeUtc", "BuyTicketsUrl", "City", "CountryCode", "CountryName", "DateLocal", "DateTimeLocal", "DateTimeUtc", "DeletedDT", "Difficulty", "DifficultyRemarks", "DurationSet1", "DurationSet2", "DurationSet3", "DurationSet4", "DurationSet5", "DurationSet6", "DurationSet7", "DurationTotal", "EndDateTimeUtc", "EndTime", "Format", "FullDuration", "Hall", "HasLiveData", "HasScoresheet", "HasTeamALost", "HasTeamAWon", "HasTeamBLost", "HasTeamBWon", "IsFreeEntrance", "IsVtsAvailable", "LastChangeDT", "LastChangeUser", "LastChangeUsername", "LineJudge1CountryCode", "LineJudge1FirstName", "LineJudge1LastName", "LineJudge2CountryCode", "LineJudge2FirstName", "LineJudge2LastName", "LineJudge3CountryCode", "LineJudge3FirstName", "LineJudge3LastName", "LineJudge4CountryCode", "LineJudge4FirstName", "LineJudge4LastName", "LiveScoreFromScoresheet", "LiveStreamUri", "LocalTimeOffset", "LoserRank", "MatchPointsA", "MatchPointsB", "MatchResultText", "MaxNbLiberos", "MaxNbPlayersInRoster", "MinNbPlayersInRoster", "NbSets", "NbSpectators", "No", "NoConfederation", "NoDocumentP2", "NoDocumentScoresheet", "NoEvent", "NoInjuriesForTeamA", "NoInjuriesForTeamB", "NoInTournament", "NoLiveScoreForJPN", "NoPool", "NoPoolRound", "NoReferee1", "NoReferee2", "NoRefereeChallenge", "NoRefereeDelegate", "NoRefereeReserve", "NoTeamA", "NoTeamB", "NoTournament", "PointsTeamASet1", "PointsTeamASet2", "PointsTeamASet3", "PointsTeamASet4", "PointsTeamASet5", "PointsTeamASet6", "PointsTeamASet7", "PointsTeamATotal", "PointsTeamBSet1", "PointsTeamBSet2", "PointsTeamBSet3", "PointsTeamBSet4", "PointsTeamBSet5", "PointsTeamBSet6", "PointsTeamBSet7", "PointsTeamBTotal", "Pool", "PoolCode", "PoolName", "PoolOrder", "PoolRoundCode", "PoolRoundName", "Referee1FederationCode", "Referee1Name", "Referee2FederationCode", "Referee2Name", "ResultType", "ResultTypeText", "ScheduleInfo", "ScorerCountryCode", "ScorerFirstName", "ScorerLastName", "Season", "Set1ResultText", "Set2ResultText", "Set3ResultText", "Set4ResultText", "Set5ResultText", "Set6ResultText", "Set7ResultText", "SetsResultsText", "SetsTotalPointsText", "Status", "TeamA", "TeamACalculatedCode", "TeamACalculatedName", "TeamACode", "TeamALiberoUniformColor", "TeamAName", "TeamAShirtColor", "TeamAText", "TeamB", "TeamBCalculatedCode", "TeamBCalculatedName", "TeamBCode", "TeamBLiberoUniformColor", "TeamBName", "TeamBShirtColor", "TeamBText", "TeamCodeA", "TeamCodeB", "TeamNameA", "TeamNameB", "TimeLocal", "Tournament", "TournamentCode", "UseForStats", "VerificationEntries", "Version", "WinnerRank"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyMatchFilter_members.html
    "Volleyball Match Filter" = c("FirstDate", "FirstDateTimeUTC", "ForLiveScore", "HeadToHeadCodes", "LastDate", "LastDateTimeUTC", "NoEvent", "NoMatches", "NoPool", "NoTeam", "NoTournament", "NoTournaments", "Statuses", "TeamCode", "TournamentGenders", "TournamentOrganizerCode", "TournamentOrganizerType", "TournamentTypes"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyPool_members.html Don't Select: TechnicalInfo
    "Volleyball Pool" = c("Code", "DeletedDT", "HasRanking", "LastChangeDT", "LastChangeUser", "LastChangeUsername", "Location", "Matches", "Name", "No", "NoConfederation", "NoRound", "NoTournament", "Order", "RankingMethod", "RoundCode", "RoundName", "Teams", "TechnicalInfo", "Tournament", "Type", "Version"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyPoolFilter_members.html
    "Volleyball Pool Filter" = c("ForRanking", "NoTournament", "Numbers"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyPoolRankingEntry_members.html
    "Volleyball Pool Ranking" = c("DeletedDT", "LastChangeDT", "LastChangeUser", "LastChangeUsername", "Matches", "MatchesAt03", "MatchesAt04", "MatchesAt13", "MatchesAt14", "MatchesAt23", "MatchesAt24", "MatchesAt30", "MatchesAt31", "MatchesAt32", "MatchesAt34", "MatchesAt40", "MatchesAt41", "MatchesAt42", "MatchesAt43", "MatchesLost", "MatchesWon", "MatchPoints", "NbMatches", "No", "NoPool", "NoTeam", "PointsLost", "PointsRatio", "PointsRatioText", "PointsWon", "Position", "Rank", "RankText", "RankTextWithRepeat", "SetsLost", "SetsRatio", "SetsRatioText", "SetsWon", "TeamCode", "TeamName", "Version"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyTeam_members.html
    "Volleyball Team" = c("AssistCoach2CtryCode", "AssistCoach2FirstName", "AssistCoach2LastName", "AssistCoach2Name", "AssistCoachCtryCode", "AssistCoachFirstName", "AssistCoachLastName", "AssistCoachName", "BestRankingSameType", "BestRankingSameTypeYear", "CanAssistantCoach2GoToBench", "CanAssistantCoachGoToBench", "CanDoctorGoToBench", "CanHeadCoachGoToBench", "CanOfficial1GoToBench", "CanOfficial2GoToBench", "CanOfficial3GoToBench", "CanOfficial4GoToBench", "CanOfficial5GoToBench", "CanTrainerGoToBench", "ClubTeam", "Code", "DeletedDT", "DoctorCtryCode", "DoctorFirstName", "DoctorId", "DoctorLastName", "DoctorName", "HeadCoachCtryCode", "HeadCoachFirstName", "HeadCoachLastName", "HeadCoachName", "HeadCoachProfile", "JournalistCtryCode", "JournalistFirstName", "JournalistLastName", "JournalistName", "LastChangeDT", "LastChangeUser", "LastChangeUsername", "LastRankingSameType", "LastRankingSameTypeYear", "LiberoUniformColor1", "LiberoUniformColor2", "LiberoUniformColor3", "ManagerCtryCode", "ManagerFirstName", "ManagerLastName", "ManagerName", "Name", "NbRank1SameType", "NbRank2SameType", "NbRank3SameType", "No", "NoBaseItem", "NoConfederation", "NoPhoto", "NoPhotoHeadCoach", "NoTournament", "Official1CtryCode", "Official1FirstName", "Official1Function", "Official1Id", "Official1LastName", "Official1Name", "Official2CtryCode", "Official2FirstName", "Official2Function", "Official2Id", "Official2LastName", "Official2Name", "Official3CtryCode", "Official3FirstName", "Official3Function", "Official3Id", "Official3LastName", "Official3Name", "Official4CtryCode", "Official4FirstName", "Official4Function", "Official4Id", "Official4LastName", "Official4Name", "Official5CtryCode", "Official5FirstName", "Official5Function", "Official5Id", "Official5LastName", "Official5Name", "Officials", "Players", "Profile", "ShirtColor1", "ShirtColor2", "ShirtColor3", "Team", "Tournament", "TournamentCode", "TournamentPlayerDisplayMethod", "TrainerCtryCode", "TrainerFirstName", "TrainerId", "TrainerLastName", "TrainerName", "TwitterUsername", "Version", "WorldRankingRank"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyTeamFilter_members.html
    "Volleyball Team Filter" = c("NoBaseItem", "NoTournament", "NoTournaments", "TournamentTeamType"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyPlayer_members.html
    "Volleyball Player" = c("AntiDopingCourseCompleteDate", "Birthdate", "Block", "ClubFederationCode", "ClubName", "ClubNameAndFederationCode", "DeletedDT", "FederationCodePlayer", "FederationNamePlayer", "FirstNamePlayer", "Gender", "Handedness", "HasProfile", "Height", "IsCaptain", "IsLibero", "IsPreselected", "IsSelected", "LastChangeDT", "LastChangeUser", "LastChangeUsername", "LastNameFirstNamePlayer", "LastNamePlayer", "NbSelOG", "NbSelOther", "NbSelTotal", "NbSelWC", "No", "NoConfederation", "NoEvent", "NoPhoto", "NoPlayer", "NoShirt", "NoTeam", "NoTournament", "PhotoUrl", "Player", "Position", "Profile", "Spike", "TeamNamePlayer", "Tournament", "TournamentCode", "Version", "Weight", "Year1stIntlSel"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyPlayerFilter_members.html
    "Volleyball Player Filter" = c("ForPublicDisplay", "NoEvent", "NoPlayer", "NoTeam", "NoTournament", "NoTournaments", "Numbers", "OnlyWithNoShirt"),
    ## Properties for non-scoring skills (Dig, Libero, Reception and Set)
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyRanking+Digger_members.html
    "Volleyball Player Ranking DERL" = c("Continues", "CourtPosition", "Excellents", "Faults", "FirstName", "Keys", "LastName", "NbMatches", "NbSets", "No", "NoShirt", "Note", "NoTeam", "NoteText", "Position", "Rank", "RankText", "TeamCode", "TeamName", "TotalAttempts"),
    ## Properties for scoring skills (Block, Serve and Spike)
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyRanking+Spiker_members.html
    "Volleyball Player Ranking ABS" = c("Continues", "CourtPosition", "Faults", "FirstName", "Keys", "LastName", "NbMatches", "NbSets", "No", "NoShirt", "Note", "NoTeam", "NoteText", "Position", "Rank", "RankText", "Successes", "TeamCode", "TeamName", "TotalAttempts"),
    ## Properties for scorers
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyRanking+Scorer_members.html
    "Volleyball Player Ranking C" = c("Blocks", "CourtPosition", "FirstName", "Keys", "LastName", "NbMatches", "NbSets", "No", "NoShirt", "Note", "NoTeam", "NoteText", "Position", "Rank", "RankText", "Services", "Spikes", "TeamCode", "TeamName", "TotalPoints"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyStatistic_members.html
    "Volleyball Statistic" = c("AttemptTotal", "BackSpikeContinue", "BackSpikeContinuePercentage", "BackSpikeEfficiencyPercentage", "BackSpikeFault", "BackSpikeFaultPercentage", "BackSpikeFaultSideOut", "BackSpikeKey", "BackSpikePoint", "BackSpikePointAverageByMatch", "BackSpikePointAverageBySet", "BackSpikePointPercentage", "BackSpikeSideOut", "BackSpikeTotal", "BeachMatch", "BlockContinue", "BlockContinuePercentage", "BlockEfficiencyPercentage", "BlockFault", "BlockFaultPercentage", "BlockFaultSideOut", "BlockKey", "BlockPoint", "BlockPointAverageByMatch", "BlockPointAverageBySet", "BlockPointPercentage", "BlockSideOut", "BlockTotal", "DigContinue", "DigContinuePercentage", "DigEfficiencyPercentage", "DigExcellent", "DigExcellentAverageByMatch", "DigExcellentAverageBySet", "DigExcellentPercentage", "DigFault", "DigFaultPercentage", "DigFaultSideOut", "DigKey", "DigTotal", "FaultTotal", "ItemType", "NbMatches", "NbRallies", "NbSets", "No", "NoItem", "NoMatch", "NoSet", "NoShirt", "NoTournament", "OpponentError", "PointAverageByMatch", "PointAverageBySet", "PointTotal", "RalliesPercentage", "ReceptionContinue", "ReceptionContinuePercentage", "ReceptionEfficiencyPercentage", "ReceptionExcellent", "ReceptionExcellentAverageByMatch", "ReceptionExcellentAverageBySet", "ReceptionExcellentPercentage", "ReceptionFault", "ReceptionFaultPercentage", "ReceptionKey", "ReceptionTotal", "ScorerPointsPercentage", "ScorerTotalAttempts", "ScorerTotalFaults", "ServeContinue", "ServeContinuePercentage", "ServeEfficiencyPercentage", "ServeFault", "ServeFaultPercentage", "ServeFaultSideOut", "ServeKey", "ServePoint", "ServePointAverageByMatch", "ServePointAverageBySet", "ServePointPercentage", "ServeTotal", "SetContinue", "SetContinuePercentage", "SetEfficiencyPercentage", "SetExcellent", "SetExcellentAverageByMatch", "SetExcellentAverageBySet", "SetExcellentPercentage", "SetFault", "SetFaultPercentage", "SetFaultSideOut", "SetKey", "SetTotal", "SpikeContinue", "SpikeContinuePercentage", "SpikeEfficiencyPercentage", "SpikeFault", "SpikeFaultPercentage", "SpikeFaultSideOut", "SpikeKey", "SpikePoint", "SpikePointAverageByMatch", "SpikePointAverageBySet", "SpikePointPercentage", "SpikeSideOut", "SpikeTotal", "TeamFault", "TimePlayed", "TimePlayedPercentage"),
    ## https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyStatisticFilter_members.html
    "Volleyball Statistic Filter" = c("MatchesToUse", "NoMatches", "NoPlayer", "NoTournaments"),
    stop("unexpected fields type: ", type)
  )
}

## internal helper function, retrieve the fields from the web page
## e.g.
# url <- "https://www.fivb.org/VisSDK/Fivb.Vis.DataWPF/Fivb.Vis.DataWPF~Fivb.Vis.Volley.VolleyPoolRankingEntry_members.html"
# cat(paste(v_get_fields(url)[[5]]$Name, collapse = "\", \""))
v_get_fields <- function(url, selector) {
  this <- rvest::html_table(xml2::read_html(url))
  return(this)
  if (is.list(this) && !is.data.frame(this)) {
    idx <- vapply(this, function(z) is.data.frame(z) && all(c("name", "type", "description") %in% tolower(colnames(z))), FUN.VALUE = TRUE)
    this <- if (sum(idx) == 1) this[[which(idx)]] else NULL
  }
  if (!is.null(this) && is.data.frame(this)) this$Name else NULL
}
